language: java
install: skip

os: linux
dist: trusty
jdk: openjdk8

before_cache:
  - rm -f  ${HOME}/.gradle/caches/modules-2/modules-2.lock
  - rm -fr ${HOME}/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - ${HOME}/.gradle/caches/
    - ${HOME}/.gradle/wrapper/

jobs:
  include:
    - if: branch = main
      script: pipeline/build.sh
    - if: branch = main AND tag IS present AND type != pull_request
      script: pipeline/build.sh && pipeline/push.sh


